### ISSUE TITLE
launch error

### ISSUE THREAD

**Issue by DisasteR** [h3llrais3r/Auto-Subliminal#10]
Can't launch from any branch...

INFO: Initializing variables and loading config.
********************************************************************
ERROR: Not a valid configuration file! Using default values instead!
********************************************************************
ERROR: Required config section is missing. Using default values instead.
ERROR: Required variable PATH is missing. Using current working directory instead.
ERROR: Required variable VIDEOPATHS is missing. Using current working directory instead.
ERROR: Required variable LOGFILE is missing. Using 'AutoSuliminal.log' instead.
ERROR: The webserver section is required. Now setting the default values (0.0.0.0:8083).
WARNING: The webserver is started without authentication.
INFO: Starting output to log.
INFO: Bye.
[15/Oct/2016:10:31:52] ENGINE Bus STARTING
[15/Oct/2016:10:31:52] ENGINE Starting WebSocket processing
[15/Oct/2016:10:31:52] ENGINE Serving on http://0.0.0.0:8083
[15/Oct/2016:10:31:52] ENGINE Bus STARTED
[15/Oct/2016:10:31:53] HTTP 
Request Headers:
  CONNECTION: keep-alive
  REFERER: http://localhost:8083/
  HOST: localhost:8083
  UPGRADE-INSECURE-REQUESTS: 1
  Remote-Addr: 127.0.0.1
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[15/Oct/2016:10:31:53] HTTP 
Traceback (most recent call last):
  File "/tmp/Auto-Subliminal/cherrypy/_cprequest.py", line 678, in respond
    inst.set_response()
  File "/tmp/Auto-Subliminal/cherrypy/_cperror.py", line 275, in set_response
    response.body = ntob("<br />\n".join(msgs), 'utf-8')
  File "/tmp/Auto-Subliminal/cherrypy/_cpcompat.py", line 54, in ntob
    assert_native(n)
  File "/tmp/Auto-Subliminal/cherrypy/_cpcompat.py", line 89, in assert_native
    raise TypeError("n must be a native str (got %s)" % type(n).__name__)
TypeError: n must be a native str (got unicode)
2016-10-15 10:31:53,927 ERROR [15/Oct/2016:10:31:53] HTTP 
Traceback (most recent call last):
  File "/tmp/Auto-Subliminal/cherrypy/_cprequest.py", line 678, in respond
    inst.set_response()
  File "/tmp/Auto-Subliminal/cherrypy/_cperror.py", line 275, in set_response
    response.body = ntob("<br />\n".join(msgs), 'utf-8')
  File "/tmp/Auto-Subliminal/cherrypy/_cpcompat.py", line 54, in ntob
    assert_native(n)
  File "/tmp/Auto-Subliminal/cherrypy/_cpcompat.py", line 89, in assert_native
    raise TypeError("n must be a native str (got %s)" % type(n).__name__)
TypeError: n must be a native str (got unicode)
127.0.0.1 - - [15/Oct/2016:10:31:53] "GET / HTTP/1.1" 500 513 "http://localhost:8083/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0"
127.0.0.1 - - [15/Oct/2016:10:31:54] "GET /favicon.ico HTTP/1.1" 200 4286 "http://localhost:8083/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0"

**Comment by h3llrais3r** [comment]
Seems to be a problem with cherrypy (since the upgrade) and the fact that you are starting the application for the first time (and you don't have a config file). CherryPy does not longer accept unicode... it should be a native str. As workaround for now, please add /home to the path, go to settings, adapt them to your needs and save it. From now on it should work.
I'll keep this open until I release a fix.

**Comment by h3llrais3r** [comment]
Please try again and let me know if it's ok now.
