### ISSUE TITLE
webpage not loading

### ISSUE THREAD

**Issue by vrtlspd** [h3llrais3r/Auto-Subliminal#144]
### INFO

**OS: Armbian 5.73
**Version:  Debian GNU/Linux 9 (stretch) 4.14.98-mvebu
**Git branch: master
**Git version: 2.11.0
**Python version: 2.7.13

**What did you do: updated distribution and I think python version was also updated
**What did you expect: to be able to open the webpage as before
**What happened: it's not longer opening "500 Internal Server Error"

### ERROR
```
  HOST: 192.168.1.250:8083
  UPGRADE-INSECURE-REQUESTS: 1
  CACHE-CONTROL: no-cache
  Remote-Addr: 192.168.1.108
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
  ACCEPT-LANGUAGE: en-GB,pt;q=0.8,en-US;q=0.5,en;q=0.3
  ACCEPT-ENCODING: gzip, deflate
[20/Mar/2019:15:43:09] HTTP
Traceback (most recent call last):
  File "/home/vspeed/Auto-Subliminal/lib/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/home/vspeed/Auto-Subliminal/lib/cherrypy/_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "/home/vspeed/Auto-Subliminal/lib/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/vspeed/Auto-Subliminal/lib/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/vspeed/Auto-Subliminal/autosubliminal/server/web/home.py", line 20, in index
    return PageTemplate(filename='/home/home.mako').render()
  File "/home/vspeed/Auto-Subliminal/autosubliminal/templates/page.py", line 40, in render
    return self.template.render_unicode(*args, **kwargs)
  File "/home/vspeed/Auto-Subliminal/lib/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/home/vspeed/Auto-Subliminal/lib/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/vspeed/Auto-Subliminal/lib/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/vspeed/Auto-Subliminal/lib/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/vspeed/Auto-Subliminal/cache/mako/layout/page.mako.py", line 35, in render_body
    runtime._include_file(context, u'/layout/inc_menu.mako', _template_uri)
  File "/home/vspeed/Auto-Subliminal/lib/mako/runtime.py", line 761, in _include_file
    callable_(ctx, **kwargs)
  File "/home/vspeed/Auto-Subliminal/cache/mako/layout/inc_menu.mako.py", line 70, in render_body
    __M_writer(unicode(autosubliminal.SCANDISK.name))
AttributeError: 'NoneType' object has no attribute 'name'
2019-03-20 15:43:09,927 ERROR [20/Mar/2019:15:43:09] HTTP
Traceback (most recent call last):
  File "/home/vspeed/Auto-Subliminal/lib/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/home/vspeed/Auto-Subliminal/lib/cherrypy/_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "/home/vspeed/Auto-Subliminal/lib/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/vspeed/Auto-Subliminal/lib/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/vspeed/Auto-Subliminal/autosubliminal/server/web/home.py", line 20, in index
    return PageTemplate(filename='/home/home.mako').render()
  File "/home/vspeed/Auto-Subliminal/autosubliminal/templates/page.py", line 40, in render
    return self.template.render_unicode(*args, **kwargs)
  File "/home/vspeed/Auto-Subliminal/lib/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/home/vspeed/Auto-Subliminal/lib/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/vspeed/Auto-Subliminal/lib/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/vspeed/Auto-Subliminal/lib/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/vspeed/Auto-Subliminal/cache/mako/layout/page.mako.py", line 35, in render_body
    runtime._include_file(context, u'/layout/inc_menu.mako', _template_uri)
  File "/home/vspeed/Auto-Subliminal/lib/mako/runtime.py", line 761, in _include_file
    callable_(ctx, **kwargs)
  File "/home/vspeed/Auto-Subliminal/cache/mako/layout/inc_menu.mako.py", line 70, in render_body
    __M_writer(unicode(autosubliminal.SCANDISK.name))
AttributeError: 'NoneType' object has no attribute 'name'
192.168.1.108 - - [20/Mar/2019:15:43:10] "GET /home/ HTTP/1.1" 500 2807 "" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0"
192.168.1.108 - - [20/Mar/2019:15:43:11] "GET /favicon.ico HTTP/1.1" 200 4286 "" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0"

```

**Comment by h3llrais3r** [comment]
That's probably because of the Python version update...
Try the development branch (which supports switch of Python version) or clear you cache folder and restart. It's also a good idea to delete all your `.pyd` files after switching to another Python version.

**Comment by vrtlspd** [comment]
hi,

sorry for taking so long. yes, my folder has around 1k files.
It seems to be now working fine.

Thanks a lot
Keep the good work
