### ISSUE TITLE
Addic7ed : loggin failed

### ISSUE THREAD

**Issue by TexGG** [h3llrais3r/Auto-Subliminal#164]
### INFO

**OS: Windows**
**Version: 3.0.0**
**Git branch: master**
**Git version: cbae06b**
**Python version: 3.7.3**

**What did you do: Used Addic7ed account**
**What did you expect: Successefully get subtitles from Addic7ed**
**What happened: Loggin failed**

It seem that it's waiting for a captcha, even if that when you log manually with browser, ti do not ask anything ... I printed the begining of the http response so you can see the first word are "Bad captcha".

### ERROR
2019-04-22 12:06:55,098 ERROR Unexpected error in provider 'addic7ed'
Traceback (most recent call last):
  File "G:\Documents\Dev\Git\Auto-Subliminal\lib\subliminal\core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "G:\Documents\Dev\Git\Auto-Subliminal\lib\subliminal\core.py", line 72, in __getitem__
    provider.initialize()
  File "G:\Documents\Dev\Git\Auto-Subliminal\lib\subliminal\providers\addic7ed.py", line 115, in initialize
    raise AuthenticationError(self.username)
subliminal.exceptions.AuthenticationError: MyAccount
2019-04-22 12:06:55,306 ERROR b'**Bad captcha**\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML

**Comment by TexGG** [comment]
By the way, I tried with changing the "server.url" from "http://www.addic7ed.com/" to "https://www.addic7ed.com/"

**Comment by h3llrais3r** [comment]
Problem is caused by changes in addic7ed website. See https://github.com/Diaoul/subliminal/issues/966.
Exclude addic7ed from your providers until a solution is found/implemented.

**Comment by h3llrais3r** [comment]
Workaround by either using captcha solver or using cookie (4c6ad4de4b211dcf0bfe056e57150f5a828e5c7c).
