### ISSUE TITLE
Trace error

### ISSUE THREAD

**Issue by sjosz** [h3llrais3r/Auto-Subliminal#28]
I love your tool, it succesfully runs on my Ubuntu 16.04 VM. However, it does not run on my VPS (also Ubuntu 16.04) where I would like it to run, I receive the following error:

```
ubuntu@vpsbox:/tmp/Auto-Subliminal$ sudo python AutoSubliminal.py                INFO: Initializing variables and loading config.

********************************************************************
ERROR: Not a valid configuration file! Using default values instead!
********************************************************************
ERROR: Required config section is missing. Using default values instead.
ERROR: Required variable PATH is missing. Using current working directory instead.
ERROR: Required variable VIDEOPATHS is missing. Using current working directory instead.
ERROR: Required variable LOGFILE is missing. Using 'AutoSuliminal.log' instead.
ERROR: The webserver section is required. Now setting the default values (0.0.0.0:8083).
WARNING: The webserver is started without authentication.
Traceback (most recent call last):
  File "AutoSubliminal.py", line 134, in <module>
    sys.exit(main())
  File "AutoSubliminal.py", line 100, in main
    import autosubliminal.application
  File "/tmp/Auto-Subliminal/autosubliminal/application.py", line 15, in <module>
    from autosubliminal.subchecker import SubChecker
  File "/tmp/Auto-Subliminal/autosubliminal/subchecker.py", line 15, in <module>
    from subliminal.providers.thesubdb import TheSubDBSubtitle
  File "/tmp/Auto-Subliminal/lib/subliminal/providers/thesubdb.py", line 13, in <module>
    language_converters.register('thesubdb = subliminal.converters.thesubdb:TheSubDBConverter')
  File "/tmp/Auto-Subliminal/lib/babelfish/converters/__init__.py", line 275, in register
    raise ValueError('Already registered')
ValueError: Already registered
```

Would someone know what to do to fix this? I tried running the setup again and I've tried a working config from the Ubuntu VM setup. There is no log unfortunately. Tnx!

**Comment by h3llrais3r** [comment]
Which version are you running?
Please fill in all the fields in the issue template.

**Comment by h3llrais3r** [comment]
Closing this for now, due to lack of information.
I will reopen when you provide the necessary info.

### INFO

**OS:**
**Version:**
**Git branch:**
**Git version:**
**Python version:**

**What did you do:**
**What did you expect:**
**What happened:**


### ERROR
```
PASTE LOGS HERE (ENABLE DEBUG LOGGING BEFORE REPRODUCING)
```
