### ISSUE TITLE
Error binding parameter 9

### ISSUE THREAD

**Issue by webnar** [h3llrais3r/Auto-Subliminal#30]
Hi,

Love the app. But i this error very often:

```
2018-03-07 20:34:15,924 ERROR    Error binding parameter 9 - probably unsupported type.
Traceback (most recent call last):
  File "C:\ProgramData\AutoSubliminal\autosubliminal\diskscanner.py", line 62, in run
    new_wanted_items.extend(walk_dir(videodir))
  File "C:\ProgramData\AutoSubliminal\autosubliminal\diskscanner.py", line 137, in walk_dir
    db.set_wanted_item(wanted_item)
  File "C:\ProgramData\AutoSubliminal\autosubliminal\db.py", line 147, in set_wanted_item
    wanted_item['imdbid']])
InterfaceError: Error binding parameter 9 - probably unsupported type.
```

Also my webif is most of the time unreachable:

`Error 500 Internal Server Error - Please refresh! If this error doesn't go away (after a few minutes), seek help! `

**Comment by h3llrais3r** [comment]
Please fill in the issue template completely and post debug logging.
Without debug logging and details it's impossible to check what's going on.

**Comment by webnar** [comment]
Bedank voor de snelle reactie.

Dit komt uit de cherrypy.error.log en veroorzaakt de WEBIF problemen.:

`[10/Mar/2018:13:57:42] ENGINE Starting WebSocket processing
[10/Mar/2018:13:57:42] ENGINE Serving on http://0.0.0.0:9996
[10/Mar/2018:13:57:42] ENGINE Bus STARTED
[10/Mar/2018:13:57:52] HTTP 
Request Headers:
  CONNECTION: keep-alive
  REFERER: http://192.168.0.94:9996/config/general/
  HOST: 192.168.0.94:9996
  UPGRADE-INSECURE-REQUESTS: 1
  Remote-Addr: 192.168.0.93
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
  COOKIE: advanced_toggle_checked=0; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; wanted_view=thumb; __zlcmid=kih58pUE3ttysf; __zlcprivacy=1; _pk_id.1.1381=c8c7ca413be2ba81.1516576267.23.1519806747.1519806747.
  ACCEPT-LANGUAGE: nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6
  ACCEPT-ENCODING: gzip, deflate
[10/Mar/2018:13:57:52] HTTP 
Traceback (most recent call last):
  File "C:\ProgramData\AutoSubliminal\lib\cherrypy\_cprequest.py", line 631, in respond
    self._do_respond(path_info)
  File "C:\ProgramData\AutoSubliminal\lib\cherrypy\_cprequest.py", line 690, in _do_respond
    response.body = self.handler()
  File "C:\ProgramData\AutoSubliminal\lib\cherrypy\lib\encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\ProgramData\AutoSubliminal\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\ProgramData\AutoSubliminal\autosubliminal\webserver.py", line 36, in index
    return str(tmpl)
  File "C:\ProgramData\AutoSubliminal\lib\Cheetah\Template.py", line 1005, in __str__
    rc = getattr(self, mainMethName)()
  File "C:\ProgramData\AutoSubliminal\autosubliminal\templates\PageTemplate.py", line 204, in respond
    self._handleCheetahInclude(VFN(VFSL([locals()]+SL+[globals(), builtin],"os.path",True),"join",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"autosubliminal.PATH",True),"encode",False)(), "web/templates/layout/inc_footer.tmpl"), trans=trans, includeFrom="file", raw=False)
  File "C:\ProgramData\AutoSubliminal\lib\Cheetah\Template.py", line 1615, in _handleCheetahInclude
    self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
  File "_ProgramData_AutoSubliminal_web_templates_layout_inc_footer_tmpl.py", line 94, in respond
  File "C:\ProgramData\AutoSubliminal\autosubliminal\utils.py", line 285, in get_next_scheduler_run_in_ms
    if scheduler.running:
AttributeError: 'NoneType' object has no attribute 'running'`

**Comment by h3llrais3r** [comment]
@webnar Please only post in English (although I understand what you mean :smile:)
This is not the debug log either. 
You must enable the debug logging in the config section and then restart the application.
This will log debug info in the `autosubliminal.log` which will give me the required info.

As far as I can see, you are running the master branch, which still contains an error when the page is loaded when not all schedulers are started.

PS: please update your original post with the all the required data:

### INFO

**OS:**
**Version:**
**Git branch:**
**Git version:**
**Python version:**

**What did you do:**
**What did you expect:**
**What happened:**


### ERROR
```
PASTE LOGS HERE (ENABLE DEBUG LOGGING BEFORE REPRODUCING)
```

**Comment by h3llrais3r** [comment]
I'll reopen once you provide a proper debug log.
