### ISSUE TITLE
ValueError: ' fr' is not a valid language

### ISSUE THREAD

**Issue by thezoggy** [h3llrais3r/Auto-Subliminal#302]
passing this along via complaint I saw on irc

They just installed latest version via git on ubuntu 18.04 and ran into tracebacks.
Looks like the leading space is causing the value error?
```
Traceback (most recent call last):
  File "/home/keith/tmp/Auto-Subliminal-3.0.0/autosubliminal/diskscanner.py", line 94, in _scan_path
    wanted_item = self._scan_file(dirname, filename)
  File "/home/keith/tmp/Auto-Subliminal-3.0.0/autosubliminal/diskscanner.py", line 132, in _scan_file
    wanted_languages=wanted_languages)
  File "/home/keith/tmp/Auto-Subliminal-3.0.0/autosubliminal/util/filesystem.py", line 131, in check_missing_subtitle_languages
    additional_language = Language.fromietf(language)
  File "/home/keith/tmp/Auto-Subliminal-3.0.0/lib/babelfish/language.py", line 126, in fromietf
    language = cls(language_subtag)
  File "/home/keith/tmp/Auto-Subliminal-3.0.0/lib/babelfish/language.py", line 82, in __init__
    raise ValueError('%r is not a valid language' % language)
ValueError: ' fr' is not a valid language
```

**Comment by h3llrais3r** [comment]
Thanks for reporting, but it seems that you have indeed a space before one of your additional languages.

Please remove the space from your additional languages, it should be a comma separated list of language codes, without spaces.

Save the config and try again, it should work. 😉
