### ISSUE TITLE
[Request] Telegram notifier?

### ISSUE THREAD

**Issue by schumi2004** [h3llrais3r/Auto-Subliminal#32]
Could you consider adding Telegram as a notifier?

**Comment by h3llrais3r** [comment]
@schumi2004 Telegram notifier added in `development` branch.
Are you willing to test it since I don't have a telegram account?

**Comment by schumi2004** [comment]
It works but something makes it crash now.

2018-03-13 19:28:55,726 ERROR    Releasing wanted queue lock with force due to exception
Traceback (most recent call last):
  File "/volume1/@appstore/scripts/Auto-Subliminal/autosubliminal/utils.py", line 469, in wrapper
    return func(*args, **kwargs)
  File "/volume1/@appstore/scripts/Auto-Subliminal/autosubliminal/subchecker.py", line 85, in run
    subtitles, language, single = _search_subtitles(video, lang, True, provider_pool)
  File "/volume1/@appstore/scripts/Auto-Subliminal/autosubliminal/subchecker.py", line 540, in _search_subtitles
    only_one=True)
  File "/volume1/@appstore/scripts/Auto-Subliminal/lib/subliminal/core.py", line 261, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/volume1/@appstore/scripts/Auto-Subliminal/lib/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/volume1/@appstore/scripts/Auto-Subliminal/lib/subliminal/providers/opensubtitles.py", line 102, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'movie'}))
  File "/volume1/@appstore/scripts/Auto-Subliminal/lib/subliminal/subtitle.py", line 241, in guess_matches
    if video.format and 'format' in guess and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'

**Comment by h3llrais3r** [comment]
Do you have the full debug log? This seems to be a know issue in subliminal itself, but I need to confirm it with the debug log.

**Comment by schumi2004** [comment]
Here you go https://ctrlv.it/id/104802/2646000505

**Comment by h3llrais3r** [comment]
Thanks, issue is indeed linked to existing guessit issue. A PR is already pending for this. See https://github.com/Diaoul/subliminal/pull/836

**Comment by h3llrais3r** [comment]
@schumi2004 Latest development version has a workaround for it. 
The application will no longer crash when subliminal crashes on the guessed format.
Instead the subtitle check will be skipped.

**Comment by schumi2004** [comment]
Workaround works perfect, thanks for your quick response .
Issue can be closed for me ;)

**Comment by h3llrais3r** [comment]
You're welcome. Thanks for testing and giving feedback. :+1:
