### ISSUE TITLE
Error while searching for subtitles for some episodes

### ISSUE THREAD

**Issue by halali** [h3llrais3r/Auto-Subliminal#36]
### INFO

**OS:**
Windows-10-10.0.16299
**Version:**
2.6.0b1 (LATEST)
**Git branch:**
development
**Git version:**
ee7afb3cd2fd70e26a3f350a6f065b05b7713b7e
**Python version:**
2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]

**What did you do:**
Manual serch for 

Vikings | 5 | 1,2 | HDTV | 720P | H264 | KILLERS

**What did you expect:**
find subtitles
**What happened:**
nothing happend

### ERROR
```
2018-04-27 10:49:52,164 INFO     Searching for an individual subtitle
2018-04-27 10:49:52,167 DEBUG    Getting wanted queue lock
2018-04-27 10:49:52,171 INFO     Searching subtitles with providers: opensubtitles
2018-04-27 10:49:52,176 INFO     Searching subtitles for video: E:\Serial\Vikings\Season 5\Vikings.S05E01-E02.720p.HDTV.x264-KILLERS.mkv
2018-04-27 10:49:52,180 INFO     Scanning video
2018-04-27 10:49:53,236 INFO     Refining episode video with custom name mappings
2018-04-27 10:49:53,239 DEBUG    Using episode min match score: 330
2018-04-27 10:49:53,243 INFO     Searching for cs subtitles
2018-04-27 10:49:53,244 DEBUG    Searching for all subtitles for video
2018-04-27 10:49:53,539 INFO     Found 3 subtitles for video
2018-04-27 10:49:56,194 ERROR    Releasing wanted queue lock with force due to exception
Traceback (most recent call last):
  File "D:\apps\Auto-Subliminal-dev\autosubliminal\util\queue.py", line 43, in wrapper
    return func(*args, **kwargs)
  File "D:\apps\Auto-Subliminal-dev\autosubliminal\subchecker.py", line 167, in search_subtitle
    for index, s in enumerate(subtitles)], key=operator.itemgetter(2), reverse=True):
  File "D:\apps\Auto-Subliminal-dev\lib\subliminal\score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "D:\apps\Auto-Subliminal-dev\lib\subliminal\providers\opensubtitles.py", line 81, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "D:\apps\Auto-Subliminal-dev\lib\subliminal\subtitle.py", line 241, in guess_matches
    if video.format and 'format' in guess and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'
```

**Comment by h3llrais3r** [comment]
Does not longer happen in master branch.
