### ISSUE TITLE
strange filename causes disk scan to stop

### ISSUE THREAD

**Issue by FSharpe** [h3llrais3r/Auto-Subliminal#37]
### INFO

**OS: ubuntu
**Version: 16.04
**Git branch: master
**Git version: 2.5.0
**Python version: 2.7.12

**What did you do: scan disk
**What did you expect: 
**What happened: scan stopped on a specific file

### ERROR

(First thanks for a great project!)

The disk scan stopped with:

2018-04-30 18:50:00,507 ERROR    Could not scan the video path (/mnt/nas/HTPC8/TV Shows), skipping it
Traceback (most recent call last):
  File "/home/odroid/Auto-Subliminal/autosubliminal/diskscanner.py", line 65, in run
    new_wanted_items.extend(walk_dir(videodir))
  File "/home/odroid/Auto-Subliminal/autosubliminal/diskscanner.py", line 140, in walk_dir
    db.set_wanted_item(wanted_item)
  File "/home/odroid/Auto-Subliminal/autosubliminal/db.py", line 149, in set_wanted_item
    wanted_item['tvdbid'],
InterfaceError: Error binding parameter 10 - probably unsupported type.

It seems multiple codecs are guessed from the filename (which has both x264 and xvid in its name). And a list can not be handled by the insert statement.

```
relevant debug log:

2018-04-30 18:50:00,395 INFO     Processing file: Code.37.S03E02.NL.VLAAMS.720p.HDTV.x264-SHOWGEMiST_xvid.avi
2018-04-30 18:50:00,395 DEBUG    Guessing file info
2018-04-30 18:50:00,477 DEBUG    Guess result: MatchesDict([('title', u'Code 37'), ('season', 3), ('episode', 2), ('language', <Language [nl]>), ('episode_title', u'VLAAMS'), ('screen_size', u'720p'), ('format', u'HDTV'), ('video_codec', [u'h264', u'XviD']), ('release_group', u'SHOWGEMiST'), ('container', u'avi'), ('mimetype', u'video/x-msvideo'), ('type', u'episode')])
2018-04-30 18:50:00,478 DEBUG    Validating guess
2018-04-30 18:50:00,478 DEBUG    Video guessed as episode
2018-04-30 18:50:00,478 DEBUG    Dict from guess: {'source': u'HDTV', 'codec': [u'h264', u'XviD'], 'episode': 2, 'quality': u'720p', 'title': u'Code 37', 'season': 3, 'year': None, 'type': u'episode', 'releasegrp': u'SHOWGEMiST'}
2018-04-30 18:50:00,478 DEBUG    Enriching dict with metadata
2018-04-30 18:50:00,495 DEBUG    Getting tvdb id for Code 37
2018-04-30 18:50:00,501 DEBUG    Tvdb id from cache: 110991
2018-04-30 18:50:00,502 DEBUG    Enriched dict: {'videopath': u'/mnt/nas/HTPC8/TV Shows/Code 37/S03/Code.37.S03E02.NL.VLAAMS.720p.HDTV.x264-SHOWGEMiST_xvid.avi', 'season': 3, 'releasegrp': u'SHOWGEMiST', 'year': None, 'quality': u'720p', 'episode': 2, 'tvdbid': 110991, 'title': u'Code 37', 'languages': [], 'source': u'HDTV', 'codec': [u'h264', u'XviD'], 'timestamp': u'2016-05-24 13:00:47', 'type': u'episode'}
2018-04-30 18:50:00,507 ERROR    Could not scan the video path (/mnt/nas/HTPC8/TV Shows), skipping it
Traceback (most recent call last):
  File "/home/odroid/Auto-Subliminal/autosubliminal/diskscanner.py", line 65, in run
    new_wanted_items.extend(walk_dir(videodir))
  File "/home/odroid/Auto-Subliminal/autosubliminal/diskscanner.py", line 140, in walk_dir
    db.set_wanted_item(wanted_item)
  File "/home/odroid/Auto-Subliminal/autosubliminal/db.py", line 149, in set_wanted_item
    wanted_item['tvdbid'],
InterfaceError: Error binding parameter 10 - probably unsupported type.
```

**Comment by vrtlspd** [comment]
fresh start. skips directory again


> 2019-01-30 01:10:10,200 ERROR Embedded subtitle track name u'English SDH' is not a valid language
> 2019-01-30 01:10:35,182 ERROR Parsing video metadata with enzyme failed
> 2019-01-30 01:10:41,921 ERROR Embedded subtitle track name u'SDH' is not a valid language
> 2019-01-30 01:10:45,398 ERROR Embedded subtitle track name u'What.If.2013.720p.BluRay.DTS.x264-LEGi0N' is not a valid language
> 2019-01-30 01:10:45,399 ERROR Embedded subtitle track name u'What.If.2013.720p.BluRay.DTS.x264-LEGi0N' is not a valid language
> 2019-01-30 01:10:49,047 ERROR Embedded subtitle track name u'The.Intern.2015.720p.BluRay.DTS.x264-LEGi0N' is not a valid language
> 2019-01-30 01:10:52,335 ERROR Embedded subtitle track name u'English FORCED' is not a valid language
> 2019-01-30 01:10:52,336 ERROR Embedded subtitle track name u'English SDH' is not a valid language
> 2019-01-30 01:10:53,754 ERROR Embedded subtitle track name u'FORCED' is not a valid language
> 2019-01-30 01:10:55,129 ERROR Embedded subtitle track name u'English Forced' is not a valid language
> 2019-01-30 01:10:57,372 ERROR Embedded subtitle track name u'English CC' is not a valid language
> 2019-01-30 01:11:05,898 ERROR Embedded subtitle track name u'SDH' is not a valid language
> 2019-01-30 01:11:24,516 ERROR Embedded subtitle track name u'SDH' is not a valid language
> 2019-01-30 01:11:40,440 ERROR Embedded subtitle track name u'English SDH' is not a valid language
> 2019-01-30 01:11:42,425 ERROR Embedded subtitle track name u'English SDH' is not a valid language
> 2019-01-30 01:11:50,156 ERROR Embedded subtitle track name u'SDH' is not a valid language
> 2019-01-30 01:11:55,479 ERROR Embedded subtitle track name u'English-Forced' is not a valid language
> 2019-01-30 01:12:03,592 ERROR Embedded subtitle track name u'forced' is not a valid language
> 2019-01-30 01:12:04,322 ERROR Embedded subtitle track name u'SDH' is not a valid language
> 2019-01-30 01:12:04,689 ERROR Element with id 0x44b4 is not in the specs
> 2019-01-30 01:12:04,690 ERROR Element with id 0x44b4 is not in the specs
> 2019-01-30 01:12:04,691 ERROR Element with id 0x44b4 is not in the specs
> 2019-01-30 01:12:04,691 ERROR Element with id 0x44b4 is not in the specs
> 2019-01-30 01:12:04,692 ERROR Element with id 0x44b4 is not in the specs
> 2019-01-30 01:12:04,692 ERROR Element with id 0x44b4 is not in the specs
> 2019-01-30 01:12:04,693 ERROR Element with id 0x44b4 is not in the specs
> 2019-01-30 01:12:04,694 ERROR Element with id 0x44b4 is not in the specs
> 2019-01-30 01:12:06,819 ERROR Embedded subtitle track name u'Creed.2015.720p.BluRay.DTS.x264-LEGi0N' is not a valid language
> 2019-01-30 01:12:07,814 ERROR Embedded subtitle track name u'English-Forced' is not a valid language
> 2019-01-30 01:12:16,240 ERROR Embedded subtitle track name u'SDH' is not a valid language
> 2019-01-30 01:12:17,329 ERROR Embedded subtitle track name u'FORCED' is not a valid language
> 2019-01-30 01:12:20,506 ERROR Embedded subtitle track name u'English-Forced' is not a valid language
> 2019-01-30 01:12:22,005 ERROR Embedded subtitle track name u'Forced' is not a valid language
> 2019-01-30 01:12:22,006 ERROR Embedded subtitle track name u'SDH' is not a valid language
> 2019-01-30 01:12:23,787 ERROR Embedded subtitle track name u'English-Forced' is not a valid language
> 2019-01-30 01:12:28,335 ERROR Could not scan the video path (/srv/dev-disk-by-label-Media/Media/Movies), skipping it
> Traceback (most recent call last):
>   File "/home/vspeed/Auto-Subliminal/autosubliminal/diskscanner.py", line 69, in run
>     new_wanted_items.extend(walk_dir(video_path))
>   File "/home/vspeed/Auto-Subliminal/autosubliminal/diskscanner.py", line 145, in walk_dir
>     db.set_wanted_item(wanted_item)
>   File "/home/vspeed/Auto-Subliminal/autosubliminal/db.py", line 211, in set_wanted_item
>     wanted_item.imdbid])
> InterfaceError: Error binding parameter 9 - probably unsupported type.
> 2019-01-30 01:12:41,676 ERROR Embedded subtitle track name u'CC' is not a valid language
> 2019-01-30 01:12:45,741 ERROR Embedded subtitle track name u'English (SDH)' is not a valid language
> 2019-01-30 01:12:45,830 ERROR Element with id 0x55b0 is not in the specs
>
