### ISSUE TITLE
sqlite3.OperationalError: no such column: video_path for every file, scanning under windows

### ISSUE THREAD

**Issue by SMylk** [h3llrais3r/Auto-Subliminal#595]
### INFO

**OS: Windows 10** 
**Version: 19042.1348**
**Git branch: default**
**Git version: 4.0.0**
**Python version: 3.10.0**

**What did you do: Trying to scan folder containing videos**
**What did you expect: Video shows up in "Home" menu**
**What happened: Nothing, pythong error**

### ERROR
```
2021-11-27 14:39:47,524 ERROR Error while scanning video file: C:\Users\WDAGUtilityAccount\Desktop\Filmek\[SubsPlease] Komi-san wa, Comyushou desu. - 05 (1080p) [28627A69].mkv
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\Auto-Subliminal-4.0.0\autosubliminal\diskscanner.py", line 89, in _scan_path
    wanted_item = self._scan_file(dirname, filename)
  File "C:\Users\WDAGUtilityAccount\Desktop\Auto-Subliminal-4.0.0\autosubliminal\diskscanner.py", line 102, in _scan_file
    wanted_item = self.wanted_db.get_wanted_item_by_video_path(os.path.join(dirname, filename), ignore_case=True)
  File "C:\Users\WDAGUtilityAccount\Desktop\Auto-Subliminal-4.0.0\autosubliminal\db\main_db.py", line 88, in get_wanted_item_by_video_path
    cursor.execute(self._query_get_by_video_path_ignore_case if ignore_case else self._query_get_by_video_path,
sqlite3.OperationalError: no such column: video_path
```

**Comment by h3llrais3r** [comment]
Is this `master` or `development` branch?
Is this a run after a new install or upgrade?
Please enable debug logging and post it here.

**Comment by h3llrais3r** [comment]
@SMylk 
I think I found the issue. Can you try the branch `hotfix_4.0.1`?
If this is working, I'll release it.

**Comment by SMylk** [comment]
was master branch after new install and now i have database.db after running hotfix, dunno before.

With 4.0.1 it finds the videos and lists them on the home page, it's working!

**Comment by h3llrais3r** [comment]
Thanks for the feedback.
Merged with master.
You can now checkout default branch again.
